### ISSUE TITLE
git pull not working

### ISSUE THREAD

**Issue by cayers71** [arthurgarzajr/MMM-DailyBibleVerse#10]
Is this module being maintained?  Git throws an error when attempting to pull the module - no such directory.

**Comment by cayers71** [comment]
disregard, was using wrong syntax.  confirmed working.

**Comment by bjec607** [comment]
This is the error I'm getting.  I copied and paste.  What was you syntax fix

**Comment by randragon42** [comment]
When in the /modules directory run:
`git clone https://github.com/arthurgarzajr/MMM-DailyBibleVerse.git`

That worked for me. 
There's a typo in the README where they left out `git clone` when they tell you to execute the install command.

**Comment by arthurgarzajr** [comment]
Sorry about that. Yes, you do need `git clone` before the repository name.
