### ISSUE TITLE
The font is too big.

### ISSUE THREAD

**Issue by GobleSt** [arthurgarzajr/MMM-DailyBibleVerse#2]
Please add an option to configure the font.

**Comment by devinhedge** [comment]
Agree. I have a patch. (and a formatting 'fix" for the hyphen).

**Comment by arthurgarzajr** [comment]
You’re free to make a pull request so that we can fix the issue.

**Comment by arthurgarzajr** [comment]
The font appears just fine for me. It may be because of the size of my mirror compared to yours.

**Comment by devinhedge** [comment]
Doing that now. Suggestion: can I make this a config parameter?

**Comment by arthurgarzajr** [comment]
Absolutely. I was thinking about making it configurable but I just hadn't gotten to it.

**Comment by devinhedge** [comment]
I really love what you've done with this module. Everyday I walk into my office and there on my 4k, 42inch monitor is my daily inspiration.

I'll fork it and let you merge it back. Just made a patch suggestion about the missing space after the hyphen and before the verse reference. Just cosmetic.

**Comment by arthurgarzajr** [comment]
Thanks! I appreciate the encouragement. And I'll approve that cosmetic change no problem. I didn't see it as an issue but now that you mention it, I do like it with a space between the hyphen and the verse.

**Comment by arthurgarzajr** [comment]
#4 allows for configuring the text size of the daily bible verse. I'll go ahead and close this issue now.
