### ISSUE TITLE
Not displaying

### ISSUE THREAD

**Issue by aa0pb** [arthurgarzajr/MMM-DailyBibleVerse#8]
Howdy,
I added the module like the readme file, but there is nothing displaying.

I do not see any errors in the log other than "No helper found for module: MMM-DailyBibleVerse"

Any thoughts?

**Comment by aa0pb** [comment]
Fixed, I must have goofed up the git clone process.  Working now.

**Comment by arthurgarzajr** [comment]
Glad you figured it out! 👍
